<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tspan_91.24</name>
   <tag></tag>
   <elementGuidId>b7449377-f4ba-4682-9295-f3bbeeaf4bc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tspan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='91.24%']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>tspan</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>91.24%</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;success&quot;)/div[1]/svg[1]/g[1]/g[2]/g[1]/g[1]/g[1]/g[1]/g[1]/g[1]/g[1]/g[1]/g[1]/g[1]/g[6]/g[1]/text[1]/tspan[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='91.24%']/parent::*</value>
   </webElementXpaths>
</WebElementEntity>
